name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: Setup Node
        working-directory: ./react
        run: npm install
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: react/src/
