name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "14"
      #     cache: "npm"
      #     cache-dependency-path: "**/package-lock.json"
      # - name: Setup Node
      #   run: npm install
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: react/src/
      - name: ESLint
        run: cd react
